services:
  db:
    image: postgres:16
    container_name: casamento_db_app
    restart: always
    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: leoPost1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # Windows
      - C:/Users/leohe/database:/var/lib/postgresql/data
      # Linux
      # - /home/leonardo/backup/20_12_24:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile # Certifique-se de que o Dockerfile esteja na raiz ou ajuste o caminho
    image: casamento:v1.3.1
    container_name: casamento_app
    volumes:
      #Linux
      # - /home/leonardo/projetos/casamento/backend/env:/root/app/env
      # - /home/leonardo/projetos/casamento/backend/files:/root/app/files

      #Windows
      - C:/Users/leohe/projetos/casamento/backend/env:/root/app/env
      - C:/Users/leohe/projetos/casamento/backend/files:/root/app/files

    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - db

    networks:
      - app-network

networks:
  app-network:
    external: true
    driver: bridge
