services:
  db:
    image: postgres:16
    container_name: casamento_db_app
    restart: always

    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: leoPost1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/leohe/database:/var/lib/postgresql/data
        #linux
        # - /home/leonardo/backup/dbeaver:/var/lib/postgresql/data

  app:
    image: casamento:v1.0.0
    container_name: casamento_app
    build: .
    volumes:
      - C:\Users\leohe\projetos\casamento\backend\env:/root/app/env
      - C:\Users\leohe\projetos\casamento\backend\files:/root/app/files
    ports:
      - "8082:8082"
    restart: "always"
