services:
  db:
    image: postgres:16
    container_name: casamento_app
    restart: always
    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: leoPost1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/leohe/database:/var/lib/postgresql/data
            #linux
            # - /home/leonardo/backup/dbeaver:/var/lib/postgresql/data

